"""
Convert pipeline JSON output to TypeScript data files for the frontend.

Usage:
    cd python
    uv run python -m src.convert_to_ts

Reads from python/output/ and writes to src/data/.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from .config import OUTPUT_DIR

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# Frontend data directory
TS_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "src" / "data"


def convert_classifications() -> None:
    """Convert classifications.json -> mongolia-classifications.ts"""
    data = json.loads((OUTPUT_DIR / "classifications.json").read_text())

    # Split into NBS and theme classifications
    nbs = [c for c in data if c["taxonomyType"] == "nbs" and c["isRelevant"]]
    themes = [c for c in data if c["taxonomyType"] == "theme" and c["isRelevant"]]

    lines = [
        'import type { ThematicClassification } from "@/types";',
        "",
        "/**",
        " * Mongolia thematic classification results.",
        " * Generated by the LLM pipeline (python/src/run_analysis.py).",
        " *",
        " * Only relevant (isRelevant: true) classifications are listed.",
        " * Any target×category combination not listed is assumed isRelevant: false.",
        " */",
        "",
        "function nbs(targetId: string, categoryId: string): ThematicClassification {",
        '  return { targetId, categoryId, taxonomyType: "nbs", isRelevant: true };',
        "}",
        "",
        "function theme(targetId: string, categoryId: string): ThematicClassification {",
        '  return { targetId, categoryId, taxonomyType: "theme", isRelevant: true };',
        "}",
        "",
    ]

    # Group NBS by category for readability
    nbs_by_cat: dict[str, list] = {}
    for c in nbs:
        cat = c["categoryId"]
        if cat not in nbs_by_cat:
            nbs_by_cat[cat] = []
        nbs_by_cat[cat].append(c["targetId"])

    lines.append("export const MONGOLIA_NBS_CLASSIFICATIONS: ThematicClassification[] = [")
    for cat_id, target_ids in sorted(nbs_by_cat.items()):
        lines.append(f"  // {cat_id} ({len(target_ids)} targets)")
        for tid in sorted(target_ids):
            lines.append(f'  nbs("{tid}", "{cat_id}"),')
        lines.append("")
    lines.append("];")
    lines.append("")

    # Group themes by category
    themes_by_cat: dict[str, list] = {}
    for c in themes:
        cat = c["categoryId"]
        if cat not in themes_by_cat:
            themes_by_cat[cat] = []
        themes_by_cat[cat].append(c["targetId"])

    lines.append("export const MONGOLIA_THEME_CLASSIFICATIONS: ThematicClassification[] = [")
    for cat_id, target_ids in sorted(themes_by_cat.items()):
        lines.append(f"  // {cat_id} ({len(target_ids)} targets)")
        for tid in sorted(target_ids):
            lines.append(f'  theme("{tid}", "{cat_id}"),')
        lines.append("")
    lines.append("];")
    lines.append("")

    lines.append("/** Combined classifications */")
    lines.append("export const MONGOLIA_CLASSIFICATIONS: ThematicClassification[] = [")
    lines.append("  ...MONGOLIA_NBS_CLASSIFICATIONS,")
    lines.append("  ...MONGOLIA_THEME_CLASSIFICATIONS,")
    lines.append("];")
    lines.append("")

    out_path = TS_DATA_DIR / "mongolia-classifications.ts"
    out_path.write_text("\n".join(lines))
    logger.info(
        f"Wrote {out_path.name}: {len(nbs)} NBS + {len(themes)} theme classifications"
    )


def convert_alignment() -> None:
    """Convert alignment.json -> mongolia-alignment.ts"""
    data = json.loads((OUTPUT_DIR / "alignment.json").read_text())

    # Only include pairs with alignment (exclude "none")
    aligned = [r for r in data if r["alignment"] != "none"]

    # Split by document pair types
    nbt_ndc = []
    nbt_nap = []
    ndc_nap = []
    other = []

    for r in aligned:
        a, b = r["targetAId"], r["targetBId"]
        # Determine document types
        a_doc = _doc_type(a)
        b_doc = _doc_type(b)
        pair_docs = sorted([a_doc, b_doc])

        if pair_docs == ["NAP", "NBSAP"]:
            nbt_nap.append(r)
        elif pair_docs == ["NBSAP", "NDC"]:
            nbt_ndc.append(r)
        elif pair_docs == ["NAP", "NDC"]:
            ndc_nap.append(r)
        else:
            other.append(r)

    lines = [
        'import type { AlignmentResult } from "@/types";',
        "",
        "/**",
        " * Mongolia pairwise alignment data.",
        " * Generated by the LLM pipeline (python/src/run_analysis.py).",
        " *",
        f" * {len(aligned)} alignment opportunities identified across 3 cross-document",
        " * comparisons: NBT×NDC, NBT×NAP, NDC×NAP.",
        " *",
        " * Only pairs with alignment (low/medium/high) are listed here.",
        ' * Any pair not listed is assumed to have "none" alignment.',
        " */",
        "",
        "function a(",
        "  targetAId: string,",
        "  targetBId: string,",
        '  alignment: "low" | "medium" | "high",',
        '  description = ""',
        "): AlignmentResult {",
        "  return { targetAId, targetBId, alignment, description };",
        "}",
        "",
    ]

    def write_section(name: str, var_name: str, items: list) -> None:
        lines.append(f"// {'=' * 60}")
        lines.append(f"// {name}")
        lines.append(f"// {'=' * 60}")
        lines.append(f"export const {var_name}: AlignmentResult[] = [")
        for r in items:
            desc = r["description"].replace('"', '\\"').replace("\n", " ")
            lines.append(f'  a("{r["targetAId"]}", "{r["targetBId"]}", "{r["alignment"]}", "{desc}"),')
        lines.append("];")
        lines.append("")

    write_section("NBT × NDC Alignment", "NBT_NDC_ALIGNMENT", nbt_ndc)
    write_section("NBT × NAP Alignment", "NBT_NAP_ALIGNMENT", nbt_nap)
    write_section("NDC × NAP Alignment", "NDC_NAP_ALIGNMENT", ndc_nap)

    if other:
        write_section("Other Alignment", "OTHER_ALIGNMENT", other)

    lines.append("/** All alignment results combined */")
    lines.append("export const MONGOLIA_ALIGNMENT: AlignmentResult[] = [")
    lines.append("  ...NBT_NDC_ALIGNMENT,")
    lines.append("  ...NBT_NAP_ALIGNMENT,")
    lines.append("  ...NDC_NAP_ALIGNMENT,")
    if other:
        lines.append("  ...OTHER_ALIGNMENT,")
    lines.append("];")
    lines.append("")

    out_path = TS_DATA_DIR / "mongolia-alignment.ts"
    out_path.write_text("\n".join(lines))
    logger.info(
        f"Wrote {out_path.name}: {len(nbt_ndc)} NBT×NDC + "
        f"{len(nbt_nap)} NBT×NAP + {len(ndc_nap)} NDC×NAP = {len(aligned)} total"
    )


def _doc_type(target_id: str) -> str:
    """Infer document type from target ID prefix."""
    if target_id.startswith("NAP_"):
        return "NAP"
    if target_id.startswith("NDC_"):
        return "NDC"
    if target_id.startswith("NBT_"):
        return "NBSAP"
    return "OTHER"


def main() -> None:
    logger.info("Converting pipeline output to TypeScript...")

    if not (OUTPUT_DIR / "classifications.json").exists():
        logger.error("classifications.json not found. Run the pipeline first.")
        return
    if not (OUTPUT_DIR / "alignment.json").exists():
        logger.error("alignment.json not found. Run the pipeline first.")
        return

    convert_classifications()
    convert_alignment()
    logger.info("Done!")


if __name__ == "__main__":
    main()
