#!/usr/bin/env python3
"""Validate country-config JSON against actual data.

Country configs in `python/data/*-country-config.json` declare document
types, default-hidden doc types, anchor doc type, country sectors, and
excluded doc types. The dashboard and pipeline trust these declarations,
so when the underlying data changes (a doc type is dropped, a sector is
added, etc.) the config can quietly drift out of sync.

Checks per country:

  1. documentTypes vs target data (targets + pseudo-target files)
  2. defaultHiddenDocTypes ⊆ documentTypes (and not a no-op)
  3. anchorDocType is declared and present in data
  4. countrySectors vs btr_data.json sectorRaw/sector
  5. excludedDocTypes ⊆ documentTypes
  6. financingLayout is a known value ("grid" | "dotmap") and "grid" has
     budget-alignment data behind it (else the slide silently falls back)

Reserved tokens (BTR, BER, BTR_ADP, OTHER) are exempt: they are
pipeline-generated or fallback labels in src/lib/utils.ts.

Exit 0 if all configs are clean, 1 if any drift is detected.

Usage:
    python python/scripts/check_country_config.py
    # or via the frontend toolchain:
    pnpm check:configs
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "python" / "data"
OUTPUT_DIR = REPO_ROOT / "python" / "output"

# Reserved doc-type tokens. These may legitimately appear in `documentTypes`
# without showing up in {country}-targets.json:
#   BTR     - generated by measure_pseudo_targets.json (every country)
#   BER     - generated by budget_pseudo_targets.json (Mongolia today)
#   BTR_ADP - synthetic visualisation key in src/lib/utils.ts:163
#   OTHER   - fallback label in src/lib/utils.ts:164
RESERVED_DOC_TOKENS = {"BTR", "BER", "BTR_ADP", "OTHER"}


def load_json(path: Path) -> object | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def collect_source_documents(country: str) -> tuple[set[str], list[str]]:
    """Return (set of doc-types in data, list of files actually read)."""
    seen: set[str] = set()
    read_files: list[str] = []

    sources = [
        DATA_DIR / f"{country}-targets.json",
        OUTPUT_DIR / country / "measure_pseudo_targets.json",
        OUTPUT_DIR / country / "budget_pseudo_targets.json",
    ]
    for path in sources:
        data = load_json(path)
        if data is None:
            continue
        records = data if isinstance(data, list) else data.get("targets", data.get("items", []))
        if not isinstance(records, list):
            continue
        for rec in records:
            if not isinstance(rec, dict):
                continue
            doc = (rec.get("sourceDocument") or rec.get("docType") or "").strip()
            if doc:
                seen.add(doc)
        read_files.append(str(path.relative_to(REPO_ROOT)))
    return seen, read_files


def collect_btr_sectors(country: str) -> tuple[set[str], str | None]:
    path = OUTPUT_DIR / country / "btr_data.json"
    data = load_json(path)
    if data is None:
        return set(), None
    measures = data.get("mitigationMeasures", []) if isinstance(data, dict) else []
    if not isinstance(measures, list):
        return set(), None
    sectors = {
        (m.get("sectorRaw") or m.get("sector") or "").strip()
        for m in measures
        if isinstance(m, dict)
    }
    sectors.discard("")
    return sectors, str(path.relative_to(REPO_ROOT))


def check_country(config_path: Path) -> tuple[bool, list[str]]:
    """Return (had_drift, lines_to_print)."""
    country = config_path.stem.replace("-country-config", "")
    config = load_json(config_path)
    if not isinstance(config, dict):
        return True, [f"checking {country}", f"  FAIL: could not load {config_path.name}"]

    declared_doc_types = [d["id"] for d in config.get("documentTypes", []) if isinstance(d, dict) and "id" in d]
    declared_set = set(declared_doc_types)
    hidden = list(config.get("defaultHiddenDocTypes") or [])
    excluded = list(config.get("excludedDocTypes") or [])
    anchor = config.get("anchorDocType")
    sectors_declared = [s["id"] for s in config.get("countrySectors", []) if isinstance(s, dict) and "id" in s]

    in_data, target_files = collect_source_documents(country)
    btr_sectors, btr_file = collect_btr_sectors(country)

    out: list[str] = [f"checking {country}"]
    drift = False

    # 1. documentTypes vs data
    declared_unused = sorted([d for d in declared_set - in_data if d not in RESERVED_DOC_TOKENS])
    undeclared_in_data = sorted([d for d in in_data - declared_set if d not in RESERVED_DOC_TOKENS])
    if declared_unused or undeclared_in_data:
        out.append("  documentTypes:")
        if declared_unused:
            out.append(f"    DRIFT: declared but unused in data: {', '.join(declared_unused)}")
            drift = True
        if undeclared_in_data:
            out.append(f"    DRIFT: present in data but undeclared: {', '.join(undeclared_in_data)}")
            drift = True
    else:
        skipped_reserved = sorted((declared_set - in_data) & RESERVED_DOC_TOKENS)
        suffix = f" (reserved skipped: {', '.join(skipped_reserved)})" if skipped_reserved else ""
        out.append(f"  documentTypes: OK ({len(declared_set)} declared, {len(in_data)} present){suffix}")

    # 2. defaultHiddenDocTypes
    if hidden:
        line = "  defaultHiddenDocTypes:"
        hidden_lines: list[str] = []
        for entry in hidden:
            if entry not in declared_set:
                hidden_lines.append(f"    DRIFT: {entry} is hidden but not declared in documentTypes")
                drift = True
            elif entry not in in_data and entry not in RESERVED_DOC_TOKENS:
                hidden_lines.append(f"    WARNING: {entry} is hidden by default but never appears in data (no-op)")
        if hidden_lines:
            out.append(line)
            out.extend(hidden_lines)
        else:
            out.append(f"  defaultHiddenDocTypes: OK ({len(hidden)} entries)")
    else:
        out.append("  defaultHiddenDocTypes: OK (empty)")

    # 3. anchorDocType
    if anchor:
        problems: list[str] = []
        if anchor not in declared_set:
            problems.append(f"DRIFT: anchorDocType {anchor!r} not declared in documentTypes")
            drift = True
        if anchor not in in_data and anchor not in RESERVED_DOC_TOKENS:
            problems.append(f"DRIFT: anchorDocType {anchor!r} declared but no targets present in data")
            drift = True
        if problems:
            out.append("  anchorDocType:")
            for p in problems:
                out.append(f"    {p}")
        else:
            out.append(f"  anchorDocType ({anchor}): OK")
    else:
        out.append("  anchorDocType: skipped (none declared)")

    # 4. countrySectors vs BTR data
    if sectors_declared:
        if btr_file is None:
            out.append("  countrySectors: skipped (btr_data.json not found)")
        else:
            declared_sectors = set(sectors_declared)
            missing_in_data = sorted(declared_sectors - btr_sectors)
            undeclared_in_data_s = sorted(btr_sectors - declared_sectors)
            if missing_in_data or undeclared_in_data_s:
                out.append("  countrySectors:")
                if missing_in_data:
                    out.append(f"    DRIFT: declared but not in btr_data.json: {', '.join(missing_in_data)}")
                    drift = True
                if undeclared_in_data_s:
                    out.append(f"    DRIFT: in btr_data.json but undeclared: {', '.join(undeclared_in_data_s)}")
                    drift = True
            else:
                out.append(
                    f"  countrySectors: OK ({len(declared_sectors)} declared, "
                    f"{len(btr_sectors)} present)"
                )
    else:
        out.append("  countrySectors: skipped (none declared)")

    # 6. financingLayout: known value; "grid" needs budget-alignment data
    layout = config.get("financingLayout")
    if layout is not None:
        if layout not in ("grid", "dotmap"):
            out.append("  financingLayout:")
            out.append(
                f"    DRIFT: unknown value {layout!r} (expected 'grid' or 'dotmap')"
            )
            drift = True
        elif layout == "grid":
            # The frontend fails soft to the dot-map when the grid yields no
            # rows, so absent data is a silent no-op — surface it here.
            has_budget = any(
                (OUTPUT_DIR / country).glob("**/budget_alignment.json")
            )
            if not has_budget:
                out.append("  financingLayout:")
                out.append(
                    "    WARNING: 'grid' declared but no budget_alignment.json "
                    "under output (slide will fall back to the dot-map)"
                )
            else:
                out.append("  financingLayout (grid): OK")
        else:
            out.append("  financingLayout (dotmap): OK")
    else:
        out.append("  financingLayout: skipped (none declared, defaults to dotmap)")

    # 5. excludedDocTypes ⊆ documentTypes
    if excluded:
        bad = sorted([e for e in excluded if e not in declared_set])
        if bad:
            out.append("  excludedDocTypes:")
            out.append(f"    DRIFT: excluded but not declared in documentTypes: {', '.join(bad)}")
            drift = True
        else:
            out.append(f"  excludedDocTypes: OK ({len(excluded)} entries)")
    else:
        out.append("  excludedDocTypes: skipped (none declared)")

    if not target_files:
        out.append("  note: no target data files were found for this country")

    return drift, out


def main() -> int:
    configs = sorted(DATA_DIR.glob("*-country-config.json"))
    if not configs:
        print(f"no country configs found under {DATA_DIR}", file=sys.stderr)
        return 1

    any_drift = False
    drifted_countries: list[str] = []
    for cfg in configs:
        drift, lines = check_country(cfg)
        print("\n".join(lines))
        print()
        if drift:
            any_drift = True
            drifted_countries.append(cfg.stem.replace("-country-config", ""))

    if any_drift:
        print(f"drift detected in {len(drifted_countries)} country: {', '.join(drifted_countries)}")
        return 1
    print("all configs clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
