"""End-to-end integration test for parse_panama_ber.py against the
Tablas-shape fixture Excel.

The fixture .xlsx is regenerated by `tests/fixtures/build_panama_ber_fixture.py`
when intentionally changed; the expected JSON is committed and compared
canonicalized (sorted keys, rounded floats). Diff = test fail.
"""

from __future__ import annotations

import json
from pathlib import Path

from src.parse_panama_ber import run_ingest

FIXTURE_DIR = Path(__file__).parent / "fixtures"
FIXTURE_XLSX = FIXTURE_DIR / "panama-ber-fixture.xlsx"
EXPECTED_JSON = FIXTURE_DIR / "panama-ber-fixture-expected.json"


def _canonicalize(payload: dict) -> dict:
    """Sort program/expenditure lists by code; round floats to absorb minor drift."""
    def round_floats(obj):
        if isinstance(obj, dict):
            return {k: round_floats(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [round_floats(v) for v in obj]
        if isinstance(obj, float):
            return round(obj, 4)
        return obj

    out = round_floats(payload)
    out["programs"] = sorted(out["programs"], key=lambda p: p["code"])
    out["expenditure"] = sorted(out["expenditure"], key=lambda e: e["code"])
    return out


def test_fixture_ingest_matches_expected_json():
    payload, _preview = run_ingest(FIXTURE_XLSX)
    expected = json.loads(EXPECTED_JSON.read_text())

    actual_canon = _canonicalize(payload)
    expected_canon = _canonicalize(expected)
    assert actual_canon == expected_canon, (
        "Fixture ingest output diverged from committed expected JSON. "
        "If the change is intentional, regenerate the expected JSON via:\n"
        "  python -m src.parse_panama_ber "
        "--source tests/fixtures/panama-ber-fixture.xlsx "
        "--output tests/fixtures/panama-ber-fixture-expected.json"
    )


def test_fixture_has_expected_pseudo_target_count():
    payload, _preview = run_ingest(FIXTURE_XLSX)
    # Three institutions in the fixture:
    #   AAC — 1 substantive programme
    #   ARAP — 2 substantive programmes
    #   MIAMBIENTE — 1 substantive + 1 overhead-rollup
    # = 5 pseudo-targets total.
    assert len(payload["programs"]) == 5
    assert len(payload["expenditure"]) == 5


def test_fixture_emits_overhead_rollup_for_miambiente():
    payload, _preview = run_ingest(FIXTURE_XLSX)
    overhead_codes = {p["code"] for p in payload["programs"] if "OVERHEAD" in p["code"]}
    # Only MIAMBIENTE has overhead — institution index 3 in source order
    # (AAC=1, ARAP=2, MIAMBIENTE=3).
    assert overhead_codes == {"BER_PA_03_OVERHEAD"}


def test_fixture_carries_english_descriptions_into_pseudo_targets():
    payload, _preview = run_ingest(FIXTURE_XLSX)
    descriptions = " ".join(p["description"] for p in payload["programs"])
    # English descriptions from the fixture must surface in the LLM-input text.
    assert "Line associated with airport management" in descriptions
    assert "biodiversity conservation" in descriptions


def test_fixture_pseudo_target_descriptions_disclose_tablas_source():
    """CLAUDE.md guardrail: every pseudo-target description must explicitly
    label the descriptive layer as Tablas-sourced and LLM-generated."""
    payload, _preview = run_ingest(FIXTURE_XLSX)
    for prog in payload["programs"]:
        assert "Tablas_adicionales" in prog["description"], (
            f"Programme {prog['code']} description missing source label"
        )
        assert "LLM-generated" in prog["description"], (
            f"Programme {prog['code']} description missing LLM-source disclosure"
        )


def test_fixture_currency_and_unit_match_panama_constants():
    payload, _preview = run_ingest(FIXTURE_XLSX)
    assert payload["currency"] == "PAB"
    assert payload["unit"] == "million"
    assert payload["period"] == {"start": 2015, "end": 2024}
