import type { ThematicClassification } from "@/types";

/**
 * Mongolia thematic classification results.
 * Generated by the LLM pipeline (python/src/run_analysis.py).
 *
 * Only relevant (isRelevant: true) classifications are listed.
 * Any target×category combination not listed is assumed isRelevant: false.
 */

function nbs(targetId: string, categoryId: string): ThematicClassification {
  return { targetId, categoryId, taxonomyType: "nbs", isRelevant: true };
}

function theme(targetId: string, categoryId: string): ThematicClassification {
  return { targetId, categoryId, taxonomyType: "theme", isRelevant: true };
}

export const MONGOLIA_NBS_CLASSIFICATIONS: ThematicClassification[] = [
  // nbs_1 (14 targets)
  nbs("BTR_agriculture_1", "nbs_1"),
  nbs("BTR_agriculture_2", "nbs_1"),
  nbs("NAP_10", "nbs_1"),
  nbs("NAP_11", "nbs_1"),
  nbs("NAP_12", "nbs_1"),
  nbs("NAP_13", "nbs_1"),
  nbs("NBSAP_8", "nbs_1"),
  nbs("NDC_11", "nbs_1"),
  nbs("NDC_12", "nbs_1"),
  nbs("NDC_13", "nbs_1"),
  nbs("NDC_14", "nbs_1"),
  nbs("NDC_16", "nbs_1"),
  nbs("NDC_22", "nbs_1"),
  nbs("NDC_25", "nbs_1"),

  // nbs_2 (4 targets)
  nbs("BTR_waste_2", "nbs_2"),
  nbs("NAP_5", "nbs_2"),
  nbs("NAP_6", "nbs_2"),
  nbs("NDC_4", "nbs_2"),

  // nbs_3 (6 targets)
  nbs("NAP_7", "nbs_3"),
  nbs("NBSAP_2", "nbs_3"),
  nbs("NBSAP_8", "nbs_3"),
  nbs("NDC_5", "nbs_3"),
  nbs("NDC_6", "nbs_3"),
  nbs("NDC_7", "nbs_3"),

  // nbs_4 (1 targets)
  nbs("NAP_6", "nbs_4"),

  // nbs_5 (11 targets)
  nbs("NAP_3", "nbs_5"),
  nbs("NBSAP_1", "nbs_5"),
  nbs("NBSAP_2", "nbs_5"),
  nbs("NBSAP_3", "nbs_5"),
  nbs("NBSAP_4", "nbs_5"),
  nbs("NBSAP_5", "nbs_5"),
  nbs("NBSAP_7", "nbs_5"),
  nbs("NBSAP_8", "nbs_5"),
  nbs("NDC_1", "nbs_5"),
  nbs("NDC_2", "nbs_5"),
  nbs("NDC_7", "nbs_5"),

  // nbs_6 (6 targets)
  nbs("BTR_agriculture_2", "nbs_6"),
  nbs("NAP_12", "nbs_6"),
  nbs("NAP_13", "nbs_6"),
  nbs("NBSAP_8", "nbs_6"),
  nbs("NDC_14", "nbs_6"),
  nbs("NDC_25", "nbs_6"),

  // nbs_7 (9 targets)
  nbs("BTR_agriculture_1", "nbs_7"),
  nbs("BTR_waste_2", "nbs_7"),
  nbs("NAP_8", "nbs_7"),
  nbs("NAP_9", "nbs_7"),
  nbs("NBSAP_5", "nbs_7"),
  nbs("NBSAP_7", "nbs_7"),
  nbs("NDC_11", "nbs_7"),
  nbs("NDC_19", "nbs_7"),
  nbs("NDC_9", "nbs_7"),

  // nbs_8 (6 targets)
  nbs("NAP_7", "nbs_8"),
  nbs("NBSAP_2", "nbs_8"),
  nbs("NBSAP_7", "nbs_8"),
  nbs("NBSAP_8", "nbs_8"),
  nbs("NDC_5", "nbs_8"),
  nbs("NDC_6", "nbs_8"),

  // nbs_9 (1 targets)
  nbs("NBSAP_10", "nbs_9"),

];

export const MONGOLIA_THEME_CLASSIFICATIONS: ThematicClassification[] = [
  // theme_0 (23 targets)
  theme("BTR_agriculture_1", "theme_0"),
  theme("BTR_agriculture_2", "theme_0"),
  theme("BTR_energy_6", "theme_0"),
  theme("BTR_waste_2", "theme_0"),
  theme("NAP_1", "theme_0"),
  theme("NAP_10", "theme_0"),
  theme("NAP_12", "theme_0"),
  theme("NAP_13", "theme_0"),
  theme("NAP_15", "theme_0"),
  theme("NAP_2", "theme_0"),
  theme("NAP_3", "theme_0"),
  theme("NAP_7", "theme_0"),
  theme("NAP_8", "theme_0"),
  theme("NBSAP_7", "theme_0"),
  theme("NBSAP_8", "theme_0"),
  theme("NDC_1", "theme_0"),
  theme("NDC_11", "theme_0"),
  theme("NDC_16", "theme_0"),
  theme("NDC_19", "theme_0"),
  theme("NDC_21", "theme_0"),
  theme("NDC_27", "theme_0"),
  theme("NDC_3", "theme_0"),
  theme("NDC_4", "theme_0"),

  // theme_1 (23 targets)
  theme("BTR_agriculture_1", "theme_1"),
  theme("BTR_agriculture_2", "theme_1"),
  theme("BTR_energy_1", "theme_1"),
  theme("BTR_energy_2", "theme_1"),
  theme("BTR_energy_3", "theme_1"),
  theme("BTR_energy_4", "theme_1"),
  theme("BTR_energy_5", "theme_1"),
  theme("BTR_energy_6", "theme_1"),
  theme("BTR_energy_7", "theme_1"),
  theme("BTR_energy_8", "theme_1"),
  theme("BTR_ippu_1", "theme_1"),
  theme("BTR_ippu_2", "theme_1"),
  theme("BTR_ippu_3", "theme_1"),
  theme("BTR_waste_1", "theme_1"),
  theme("BTR_waste_2", "theme_1"),
  theme("NAP_7", "theme_1"),
  theme("NBSAP_7", "theme_1"),
  theme("NDC_20", "theme_1"),
  theme("NDC_22", "theme_1"),
  theme("NDC_23", "theme_1"),
  theme("NDC_24", "theme_1"),
  theme("NDC_27", "theme_1"),
  theme("NDC_6", "theme_1"),

  // theme_10 (8 targets)
  theme("BTR_agriculture_1", "theme_10"),
  theme("BTR_energy_4", "theme_10"),
  theme("BTR_energy_7", "theme_10"),
  theme("BTR_waste_2", "theme_10"),
  theme("NAP_14", "theme_10"),
  theme("NBSAP_5", "theme_10"),
  theme("NBSAP_6", "theme_10"),
  theme("NDC_18", "theme_10"),

  // theme_2 (10 targets)
  theme("BTR_agriculture_1", "theme_2"),
  theme("BTR_agriculture_2", "theme_2"),
  theme("NAP_10", "theme_2"),
  theme("NAP_13", "theme_2"),
  theme("NAP_4", "theme_2"),
  theme("NBSAP_2", "theme_2"),
  theme("NBSAP_8", "theme_2"),
  theme("NDC_13", "theme_2"),
  theme("NDC_22", "theme_2"),
  theme("NDC_25", "theme_2"),

  // theme_3 (19 targets)
  theme("BTR_agriculture_1", "theme_3"),
  theme("NAP_3", "theme_3"),
  theme("NAP_6", "theme_3"),
  theme("NBSAP_1", "theme_3"),
  theme("NBSAP_11", "theme_3"),
  theme("NBSAP_12", "theme_3"),
  theme("NBSAP_13", "theme_3"),
  theme("NBSAP_17", "theme_3"),
  theme("NBSAP_19", "theme_3"),
  theme("NBSAP_2", "theme_3"),
  theme("NBSAP_3", "theme_3"),
  theme("NBSAP_4", "theme_3"),
  theme("NBSAP_5", "theme_3"),
  theme("NBSAP_7", "theme_3"),
  theme("NBSAP_8", "theme_3"),
  theme("NBSAP_9", "theme_3"),
  theme("NDC_1", "theme_3"),
  theme("NDC_2", "theme_3"),
  theme("NDC_7", "theme_3"),

  // theme_4 (9 targets)
  theme("BTR_energy_4", "theme_4"),
  theme("BTR_energy_5", "theme_4"),
  theme("BTR_energy_6", "theme_4"),
  theme("BTR_energy_7", "theme_4"),
  theme("BTR_ippu_2", "theme_4"),
  theme("BTR_waste_1", "theme_4"),
  theme("BTR_waste_2", "theme_4"),
  theme("NBSAP_14", "theme_4"),
  theme("NBSAP_6", "theme_4"),

  // theme_5 (3 targets)
  theme("NBSAP_20", "theme_5"),
  theme("NDC_26", "theme_5"),
  theme("NDC_27", "theme_5"),

  // theme_6 (10 targets)
  theme("BTR_agriculture_1", "theme_6"),
  theme("NAP_1", "theme_6"),
  theme("NAP_14", "theme_6"),
  theme("NAP_2", "theme_6"),
  theme("NBSAP_11", "theme_6"),
  theme("NBSAP_13", "theme_6"),
  theme("NBSAP_18", "theme_6"),
  theme("NBSAP_19", "theme_6"),
  theme("NBSAP_5", "theme_6"),
  theme("NDC_20", "theme_6"),

  // theme_7 (25 targets)
  theme("BTR_agriculture_1", "theme_7"),
  theme("BTR_agriculture_2", "theme_7"),
  theme("BTR_energy_1", "theme_7"),
  theme("BTR_energy_3", "theme_7"),
  theme("BTR_energy_5", "theme_7"),
  theme("BTR_energy_6", "theme_7"),
  theme("BTR_energy_7", "theme_7"),
  theme("BTR_energy_8", "theme_7"),
  theme("BTR_ippu_1", "theme_7"),
  theme("BTR_ippu_2", "theme_7"),
  theme("BTR_ippu_3", "theme_7"),
  theme("BTR_waste_1", "theme_7"),
  theme("BTR_waste_2", "theme_7"),
  theme("NAP_10", "theme_7"),
  theme("NBSAP_1", "theme_7"),
  theme("NBSAP_12", "theme_7"),
  theme("NBSAP_16", "theme_7"),
  theme("NBSAP_19", "theme_7"),
  theme("NBSAP_2", "theme_7"),
  theme("NBSAP_20", "theme_7"),
  theme("NBSAP_7", "theme_7"),
  theme("NBSAP_8", "theme_7"),
  theme("NBSAP_9", "theme_7"),
  theme("NDC_1", "theme_7"),
  theme("NDC_19", "theme_7"),

  // theme_8 (1 targets)
  theme("NBSAP_20", "theme_8"),

  // theme_9 (5 targets)
  theme("BTR_agriculture_1", "theme_9"),
  theme("BTR_energy_6", "theme_9"),
  theme("NBSAP_16", "theme_9"),
  theme("NBSAP_17", "theme_9"),
  theme("NBSAP_7", "theme_9"),

];

/** Combined classifications */
export const MONGOLIA_CLASSIFICATIONS: ThematicClassification[] = [
  ...MONGOLIA_NBS_CLASSIFICATIONS,
  ...MONGOLIA_THEME_CLASSIFICATIONS,
];
