import type { ThematicClassification } from "@/types";

/**
 * Mongolia thematic classification results.
 * Generated by the LLM pipeline (python/src/run_analysis.py).
 *
 * Only relevant (isRelevant: true) classifications are listed.
 * Any target×category combination not listed is assumed isRelevant: false.
 */

function nbs(targetId: string, categoryId: string): ThematicClassification {
  return { targetId, categoryId, taxonomyType: "nbs", isRelevant: true };
}

function theme(targetId: string, categoryId: string): ThematicClassification {
  return { targetId, categoryId, taxonomyType: "theme", isRelevant: true };
}

export const MONGOLIA_NBS_CLASSIFICATIONS: ThematicClassification[] = [
  // nbs_agri (12 targets)
  nbs("NAP_10", "nbs_agri"),
  nbs("NAP_11", "nbs_agri"),
  nbs("NAP_12", "nbs_agri"),
  nbs("NAP_13", "nbs_agri"),
  nbs("NBT_7", "nbs_agri"),
  nbs("NDC_AnimalHusbandry_2", "nbs_agri"),
  nbs("NDC_AnimalHusbandry_3", "nbs_agri"),
  nbs("NDC_AnimalHusbandry_4", "nbs_agri"),
  nbs("NDC_ArableFarming_1", "nbs_agri"),
  nbs("NDC_ArableFarming_2", "nbs_agri"),
  nbs("NDC_ArableFarming_3", "nbs_agri"),
  nbs("NDC_LivestockMitigation", "nbs_agri"),

  // nbs_carbon (3 targets)
  nbs("NBT_6", "nbs_carbon"),
  nbs("NDC_Forests_1", "nbs_carbon"),
  nbs("NDC_Forests_2", "nbs_carbon"),

  // nbs_ecosystem (13 targets)
  nbs("NAP_3", "nbs_ecosystem"),
  nbs("NBT_1", "nbs_ecosystem"),
  nbs("NBT_11", "nbs_ecosystem"),
  nbs("NBT_17", "nbs_ecosystem"),
  nbs("NBT_2", "nbs_ecosystem"),
  nbs("NBT_3", "nbs_ecosystem"),
  nbs("NBT_4", "nbs_ecosystem"),
  nbs("NBT_8", "nbs_ecosystem"),
  nbs("NBT_9", "nbs_ecosystem"),
  nbs("NDC_Biodiversity_1", "nbs_ecosystem"),
  nbs("NDC_Biodiversity_2", "nbs_ecosystem"),
  nbs("NDC_Forests_1", "nbs_ecosystem"),
  nbs("NDC_Forests_3", "nbs_ecosystem"),

  // nbs_forest (6 targets)
  nbs("NAP_7", "nbs_forest"),
  nbs("NBT_6", "nbs_forest"),
  nbs("NBT_7", "nbs_forest"),
  nbs("NDC_Forests_1", "nbs_forest"),
  nbs("NDC_Forests_2", "nbs_forest"),
  nbs("NDC_Forests_3", "nbs_forest"),

  // nbs_risk (7 targets)
  nbs("NAP_8", "nbs_risk"),
  nbs("NAP_9", "nbs_risk"),
  nbs("NBT_4", "nbs_risk"),
  nbs("NDC_AnimalHusbandry_2", "nbs_risk"),
  nbs("NDC_NatDisasters_1", "nbs_risk"),
  nbs("NDC_NatDisasters_2", "nbs_risk"),
  nbs("NDC_SocialProtection", "nbs_risk"),

  // nbs_soil (4 targets)
  nbs("NAP_12", "nbs_soil"),
  nbs("NAP_13", "nbs_soil"),
  nbs("NDC_ArableFarming_1", "nbs_soil"),
  nbs("NDC_Mitigation_3", "nbs_soil"),

  // nbs_urban (1 targets)
  nbs("NBT_9", "nbs_urban"),

  // nbs_water (3 targets)
  nbs("NAP_5", "nbs_water"),
  nbs("NAP_6", "nbs_water"),
  nbs("NDC_WaterResources_2", "nbs_water"),

  // nbs_wetland (1 targets)
  nbs("NAP_6", "nbs_wetland"),

];

export const MONGOLIA_THEME_CLASSIFICATIONS: ThematicClassification[] = [
  // theme_adaptation (16 targets)
  theme("NAP_1", "theme_adaptation"),
  theme("NAP_10", "theme_adaptation"),
  theme("NAP_12", "theme_adaptation"),
  theme("NAP_13", "theme_adaptation"),
  theme("NAP_2", "theme_adaptation"),
  theme("NAP_3", "theme_adaptation"),
  theme("NAP_7", "theme_adaptation"),
  theme("NAP_8", "theme_adaptation"),
  theme("NBT_6", "theme_adaptation"),
  theme("NDC_ArableFarming_2", "theme_adaptation"),
  theme("NDC_ArableFarming_3", "theme_adaptation"),
  theme("NDC_Biodiversity_1", "theme_adaptation"),
  theme("NDC_LivestockMitigation", "theme_adaptation"),
  theme("NDC_SocialProtection", "theme_adaptation"),
  theme("NDC_WaterResources_1", "theme_adaptation"),
  theme("NDC_WaterResources_2", "theme_adaptation"),

  // theme_capacity (8 targets)
  theme("NAP_14", "theme_capacity"),
  theme("NAP_2", "theme_capacity"),
  theme("NBT_10", "theme_capacity"),
  theme("NBT_12", "theme_capacity"),
  theme("NBT_17", "theme_capacity"),
  theme("NBT_18", "theme_capacity"),
  theme("NBT_4", "theme_capacity"),
  theme("NDC_Education", "theme_capacity"),

  // theme_gender (1 targets)
  theme("NBT_19", "theme_gender"),

  // theme_indigenous (3 targets)
  theme("NBT_10", "theme_indigenous"),
  theme("NBT_19", "theme_indigenous"),
  theme("NDC_Culture", "theme_indigenous"),

  // theme_land (5 targets)
  theme("NAP_13", "theme_land"),
  theme("NAP_4", "theme_land"),
  theme("NBT_2", "theme_land"),
  theme("NBT_7", "theme_land"),
  theme("NDC_Mitigation_3", "theme_land"),

  // theme_mitigation (16 targets)
  theme("NAP_10", "theme_mitigation"),
  theme("NAP_12", "theme_mitigation"),
  theme("NAP_13", "theme_mitigation"),
  theme("NAP_14", "theme_mitigation"),
  theme("NAP_7", "theme_mitigation"),
  theme("NAP_8", "theme_mitigation"),
  theme("NBT_6", "theme_mitigation"),
  theme("NBT_7", "theme_mitigation"),
  theme("NDC_ArableFarming_2", "theme_mitigation"),
  theme("NDC_ArableFarming_3", "theme_mitigation"),
  theme("NDC_Biodiversity_1", "theme_mitigation"),
  theme("NDC_Forests_2", "theme_mitigation"),
  theme("NDC_LivestockMitigation", "theme_mitigation"),
  theme("NDC_Mitigation_1", "theme_mitigation"),
  theme("NDC_Mitigation_2", "theme_mitigation"),
  theme("NDC_SocialProtection", "theme_mitigation"),

  // theme_pollution (3 targets)
  theme("NBT_12", "theme_pollution"),
  theme("NBT_13", "theme_pollution"),
  theme("NBT_5", "theme_pollution"),

  // theme_private (2 targets)
  theme("NBT_12", "theme_private"),
  theme("NBT_16", "theme_private"),

  // theme_sdg (13 targets)
  theme("NAP_10", "theme_sdg"),
  theme("NBT_11", "theme_sdg"),
  theme("NBT_12", "theme_sdg"),
  theme("NBT_13", "theme_sdg"),
  theme("NBT_15", "theme_sdg"),
  theme("NBT_19", "theme_sdg"),
  theme("NBT_5", "theme_sdg"),
  theme("NBT_7", "theme_sdg"),
  theme("NBT_8", "theme_sdg"),
  theme("NBT_9", "theme_sdg"),
  theme("NDC_Biodiversity_1", "theme_sdg"),
  theme("NDC_Biodiversity_2", "theme_sdg"),
  theme("NDC_SocialProtection", "theme_sdg"),

  // theme_species (15 targets)
  theme("NAP_3", "theme_species"),
  theme("NAP_6", "theme_species"),
  theme("NBT_1", "theme_species"),
  theme("NBT_10", "theme_species"),
  theme("NBT_11", "theme_species"),
  theme("NBT_15", "theme_species"),
  theme("NBT_17", "theme_species"),
  theme("NBT_2", "theme_species"),
  theme("NBT_3", "theme_species"),
  theme("NBT_4", "theme_species"),
  theme("NBT_8", "theme_species"),
  theme("NBT_9", "theme_species"),
  theme("NDC_Biodiversity_1", "theme_species"),
  theme("NDC_Biodiversity_2", "theme_species"),
  theme("NDC_Forests_3", "theme_species"),

];

/** Combined classifications */
export const MONGOLIA_CLASSIFICATIONS: ThematicClassification[] = [
  ...MONGOLIA_NBS_CLASSIFICATIONS,
  ...MONGOLIA_THEME_CLASSIFICATIONS,
];
