import type { AlignmentResult } from "@/types";

/**
 * Mongolia pairwise alignment data.
 * Extracted from Section 3.3 of the Mongolia report (Figures 3.3–3.5).
 *
 * 159 alignment opportunities were identified across 3 cross-document
 * comparisons: NBT×NDC, NBT×NAP, NDC×NAP.
 *
 * Only pairs with alignment (low/medium/high) are listed here.
 * Any pair not listed is assumed to have "none" alignment.
 *
 * NOTE: This is pilot data extracted from the report for prototyping.
 * In production, these results are generated by the LLM pipeline.
 */

function a(
  targetAId: string,
  targetBId: string,
  alignment: "low" | "medium" | "high",
  description = ""
): AlignmentResult {
  return { targetAId, targetBId, alignment, description };
}

// ============================================================================
// NBT × NDC Alignment (Figure 3.3)
// ============================================================================
export const NBT_NDC_ALIGNMENT: AlignmentResult[] = [
  // NBT 1 — Protected areas 30%
  a("NBT_1", "NDC_Biodiversity_1", "high", "Both focus on expanding protected area coverage and ecological connectivity"),
  a("NBT_1", "NDC_Biodiversity_2", "high", "Both aim to protect vulnerable ecosystems through monitoring and conservation"),
  a("NBT_1", "NDC_Forests_3", "medium", "Legal frameworks for forests support protected area management"),
  a("NBT_1", "NDC_Forests_1", "medium", "Forest protection contributes to protected area integrity"),

  // NBT 2 — Restore 30% degraded ecosystems
  a("NBT_2", "NDC_Biodiversity_1", "medium", "Restoration supports ecological connectivity across protected areas"),
  a("NBT_2", "NDC_Biodiversity_2", "high", "Both target ecosystem regeneration and conservation research"),
  a("NBT_2", "NDC_Forests_1", "high", "Forest regeneration directly contributes to ecosystem restoration"),
  a("NBT_2", "NDC_Forests_2", "high", "Afforestation and restoration are core to restoring degraded ecosystems"),
  a("NBT_2", "NDC_Mitigation_3", "high", "Rangeland restoration aligns with restoring degraded ecosystems"),
  a("NBT_2", "NDC_AnimalHusbandry_4", "medium", "Pasture restoration contributes to ecosystem restoration"),

  // NBT 3 — Rare species
  a("NBT_3", "NDC_Biodiversity_1", "high", "Protected areas are key to species conservation"),
  a("NBT_3", "NDC_Biodiversity_2", "high", "Targeted conservation research directly supports rare species"),

  // NBT 4 — Invasive species
  a("NBT_4", "NDC_Biodiversity_2", "medium", "Invasive species control supports ecosystem monitoring"),
  a("NBT_4", "NDC_ArableFarming_3", "low", "Pest-resistant crops relate tangentially to invasive species management"),

  // NBT 5 — Reduce pollution
  a("NBT_5", "NDC_ArableFarming_4", "low", "Environmentally friendly tech may reduce agricultural pollution"),

  // NBT 6 — GHG reduction and carbon sink
  a("NBT_6", "NDC_Forests_1", "high", "Forest protection enhances carbon sinks"),
  a("NBT_6", "NDC_Forests_2", "high", "Afforestation directly increases carbon sequestration"),
  a("NBT_6", "NDC_LivestockMitigation", "high", "Both target CO2 reduction in the agricultural/land sector"),
  a("NBT_6", "NDC_Mitigation_1", "high", "Livestock circulation reduction aligns with GHG reduction goals"),
  a("NBT_6", "NDC_Mitigation_2", "medium", "Meat supply optimization contributes to emissions reduction"),
  a("NBT_6", "NDC_Mitigation_3", "high", "Rangeland restoration reduces soil organic carbon loss"),

  // NBT 7 — Sustainable forestry and agriculture
  a("NBT_7", "NDC_Forests_1", "high", "Sustainable forestry aligns with forest protection"),
  a("NBT_7", "NDC_Forests_2", "medium", "Afforestation supports sustainable forest industry"),
  a("NBT_7", "NDC_Forests_3", "medium", "Legal framework supports sustainable forest management"),
  a("NBT_7", "NDC_ArableFarming_1", "high", "Both promote sustainable agricultural practices"),
  a("NBT_7", "NDC_ArableFarming_2", "high", "Climate-smart tech directly supports sustainable agriculture"),
  a("NBT_7", "NDC_ArableFarming_4", "medium", "Environmentally friendly tech in crop production"),
  a("NBT_7", "NDC_AnimalHusbandry_4", "medium", "Sustainable pasture management supports sustainable agriculture"),

  // NBT 8 — Ecosystem services
  a("NBT_8", "NDC_Biodiversity_1", "high", "Protected areas enhance ecosystem services"),
  a("NBT_8", "NDC_Biodiversity_2", "high", "Conservation research supports ecosystem service understanding"),
  a("NBT_8", "NDC_Forests_1", "medium", "Forest protection maintains ecosystem services"),
  a("NBT_8", "NDC_WaterResources_2", "medium", "Water sector resilience relates to ecosystem service restoration"),

  // NBT 9 — Urban biodiversity
  a("NBT_9", "NDC_Biodiversity_1", "low", "Urban protected areas are a small part of overall protected areas"),

  // NBT 11 — Biodiversity in policy
  a("NBT_11", "NDC_Forests_3", "medium", "Legal framework for forests integrates biodiversity concerns"),
  a("NBT_11", "NDC_WaterResources_1", "medium", "Policy environment improvement supports biodiversity integration"),

  // NBT 15 — Redesign subsidies
  a("NBT_15", "NDC_AnimalHusbandry_1", "low", "Subsidy reform could influence livestock market practices"),

  // NBT 17 — Scientific cooperation
  a("NBT_17", "NDC_Education", "medium", "Scientific cooperation aligns with climate education"),

  // NBT 19 — Inclusive governance
  a("NBT_19", "NDC_SocialProtection", "medium", "Both address vulnerable populations and inclusive approaches"),
  a("NBT_19", "NDC_Education", "low", "Public participation in climate education"),
];

// ============================================================================
// NBT × NAP Alignment (Figure 3.4)
// ============================================================================
export const NBT_NAP_ALIGNMENT: AlignmentResult[] = [
  // NBT 1 — Protected areas
  a("NBT_1", "NAP_3", "high", "Ecosystem adaptive capacity directly supports protected area goals"),
  a("NBT_1", "NAP_7", "medium", "Climate-resilient forests support protected area network"),

  // NBT 2 — Restore degraded ecosystems
  a("NBT_2", "NAP_3", "high", "Ecosystem adaptive capacity enables restoration"),
  a("NBT_2", "NAP_4", "high", "Both target land degradation and ecosystem restoration"),
  a("NBT_2", "NAP_7", "high", "Forest establishment directly contributes to ecosystem restoration"),
  a("NBT_2", "NAP_6", "medium", "Water resource restoration supports ecosystem restoration"),

  // NBT 3 — Rare species
  a("NBT_3", "NAP_3", "high", "Ecosystem adaptive capacity essential for rare species survival"),

  // NBT 4 — Invasive species
  a("NBT_4", "NAP_3", "medium", "Ecosystem adaptive capacity helps manage invasive species impacts"),
  a("NBT_4", "NAP_8", "low", "Disaster resilience tangentially relates to invasive species risks"),

  // NBT 6 — GHG and carbon sink
  a("NBT_6", "NAP_7", "high", "Climate-resilient forests enhance carbon sinks"),
  a("NBT_6", "NAP_3", "medium", "Ecosystem adaptive capacity supports carbon sink maintenance"),

  // NBT 7 — Sustainable agriculture/forestry
  a("NBT_7", "NAP_7", "high", "Both focus on sustainable, climate-resilient forestry"),
  a("NBT_7", "NAP_10", "high", "Sustainable livestock management aligns with sustainable agriculture"),
  a("NBT_7", "NAP_11", "medium", "Improving livestock quality supports sustainable production"),
  a("NBT_7", "NAP_12", "high", "High-yield climate-adapted crops directly align"),
  a("NBT_7", "NAP_13", "high", "Soil fertility conservation supports sustainable agriculture"),

  // NBT 8 — Ecosystem services
  a("NBT_8", "NAP_3", "high", "Adaptive capacity directly enhances ecosystem services"),
  a("NBT_8", "NAP_6", "high", "Water ecosystem service conservation is core to both"),
  a("NBT_8", "NAP_7", "medium", "Climate-resilient forests maintain ecosystem services"),

  // NBT 9 — Urban biodiversity
  a("NBT_9", "NAP_8", "low", "Disaster resilience and urban green infrastructure"),

  // NBT 11 — Biodiversity in policy
  a("NBT_11", "NAP_1", "high", "Both target policy coherence and cross-sector integration"),

  // NBT 13 — Sustainable consumption
  a("NBT_13", "NAP_2", "low", "Knowledge dissemination supports sustainable consumption education"),

  // NBT 17 — Scientific cooperation
  a("NBT_17", "NAP_2", "medium", "Both focus on knowledge sharing and capacity building"),

  // NBT 18 — Biodiversity information access
  a("NBT_18", "NAP_2", "high", "Both target improving knowledge access for decision-makers"),

  // NBT 19 — Inclusive governance
  a("NBT_19", "NAP_15", "medium", "Social safety nets and inclusive governance both support vulnerable communities"),
  a("NBT_19", "NAP_1", "low", "Policy enhancement could include inclusive governance"),
];

// ============================================================================
// NDC × NAP Alignment (Figure 3.5)
// ============================================================================
export const NDC_NAP_ALIGNMENT: AlignmentResult[] = [
  // Biodiversity × Ecosystems
  a("NDC_Biodiversity_1", "NAP_3", "high", "Both target ecosystem resilience and adaptive capacity"),
  a("NDC_Biodiversity_1", "NAP_7", "medium", "Forest resilience supports biodiversity protection"),
  a("NDC_Biodiversity_2", "NAP_3", "high", "Both focus on vulnerable ecosystem protection and monitoring"),
  a("NDC_Biodiversity_2", "NAP_6", "medium", "Water resource conservation supports ecosystem protection"),

  // Forests
  a("NDC_Forests_1", "NAP_7", "high", "Both target forest protection and resilience"),
  a("NDC_Forests_2", "NAP_7", "high", "Afforestation directly supports climate-resilient forest goals"),
  a("NDC_Forests_3", "NAP_7", "medium", "Legal framework supports climate-resilient forestry"),
  a("NDC_Forests_3", "NAP_1", "medium", "Both enhance legal and policy frameworks"),

  // Natural disasters
  a("NDC_NatDisasters_1", "NAP_8", "high", "Both target disaster risk reduction frameworks"),
  a("NDC_NatDisasters_1", "NAP_9", "high", "Both focus on early warning systems and disaster response"),
  a("NDC_NatDisasters_2", "NAP_8", "high", "Both target reducing disaster risks at all levels"),
  a("NDC_NatDisasters_2", "NAP_9", "high", "Early warning systems are central to both targets"),

  // Animal husbandry
  a("NDC_AnimalHusbandry_1", "NAP_10", "high", "Both target sustainable livestock management aligned with resources"),
  a("NDC_AnimalHusbandry_1", "NAP_11", "high", "Both improve livestock quality and reduce pasture pressure"),
  a("NDC_AnimalHusbandry_2", "NAP_10", "high", "Livestock feed/water management directly supports sustainable livestock"),
  a("NDC_AnimalHusbandry_2", "NAP_11", "medium", "Feed supply improvement supports livestock quality goals"),
  a("NDC_AnimalHusbandry_3", "NAP_10", "medium", "Smart tech in livestock supports sustainable management"),
  a("NDC_AnimalHusbandry_4", "NAP_10", "high", "Both target sustainable collaborative pasture management"),
  a("NDC_AnimalHusbandry_4", "NAP_4", "high", "Pasture restoration addresses desertification and land degradation"),

  // Livestock mitigation
  a("NDC_LivestockMitigation", "NAP_10", "high", "Ecological carrying capacity directly relates to sustainable livestock"),
  a("NDC_LivestockMitigation", "NAP_11", "medium", "Improving livestock turnover supports livestock mitigation"),
  a("NDC_Mitigation_3", "NAP_4", "high", "Both target restoration of degraded land"),
  a("NDC_Mitigation_3", "NAP_13", "high", "Soil organic carbon and soil fertility are directly related"),

  // Water
  a("NDC_WaterResources_1", "NAP_1", "medium", "Both improve policy frameworks for climate adaptation"),
  a("NDC_WaterResources_2", "NAP_5", "high", "Both focus on advanced water monitoring and management"),
  a("NDC_WaterResources_2", "NAP_6", "high", "Both target water resource conservation and restoration"),

  // Arable farming
  a("NDC_ArableFarming_1", "NAP_12", "high", "Both promote climate-adapted, high-yield crop technologies"),
  a("NDC_ArableFarming_1", "NAP_13", "high", "Minimal tillage and soil conservation directly align"),
  a("NDC_ArableFarming_2", "NAP_12", "high", "Climate-smart tech for consistent high yields"),
  a("NDC_ArableFarming_3", "NAP_12", "high", "Drought/pest-resistant varieties for climate-adapted crops"),
  a("NDC_ArableFarming_4", "NAP_12", "medium", "Environmentally friendly tech supports sustainable crop production"),
  a("NDC_ArableFarming_4", "NAP_13", "medium", "Eco-friendly tech contributes to soil conservation"),

  // Social / Health / Education
  a("NDC_PublicHealth", "NAP_14", "high", "Both target climate-related health risk preparedness"),
  a("NDC_SocialProtection", "NAP_15", "high", "Both create safety nets for climate-vulnerable communities"),
  a("NDC_Education", "NAP_2", "high", "Both promote climate knowledge, training, and public participation"),
  a("NDC_Culture", "NAP_1", "low", "Cultural heritage protection relates broadly to policy frameworks"),

  // Policy
  a("NDC_WaterResources_1", "NAP_5", "medium", "Both improve policy and monitoring for water sector"),
];

/** All alignment results combined */
export const MONGOLIA_ALIGNMENT: AlignmentResult[] = [
  ...NBT_NDC_ALIGNMENT,
  ...NBT_NAP_ALIGNMENT,
  ...NDC_NAP_ALIGNMENT,
];

